name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Check Node version
        run: node --version

      - name: Install root dependencies
        run: npm ci

      - name: Install mobile dependencies
        run: npm ci
        working-directory: mobile

      - name: Check Expo installation
        run: npx expo --version
        working-directory: mobile

      - name: Run lint
        run: npm run lint
        working-directory: mobile

      - name: Run tests
        run: npm test
        working-directory: mobile

      - name: Build mobile application
        run: npm run build
        working-directory: mobile